# Generated by Django 4.0.3 on 2022-10-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_user_adresse_remove_user_pays_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adresse',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pays',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ville',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
