# Generated by Django 4.0.3 on 2022-10-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_user_adresse_user_pays_user_ville'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_photo',
        ),
    ]
