# Generated by Django 4.0.3 on 2022-10-18 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_user_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='zipcode',
        ),
    ]
