# Generated by Django 4.0.3 on 2022-10-29 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_commande_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='statut',
        ),
    ]
