# Generated by Django 4.0.3 on 2022-11-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_expiration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
