# Generated by Django 4.0.3 on 2022-11-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_cart_ordered_remove_cart_ordered_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='valider',
            field=models.BooleanField(default=False),
        ),
    ]
