# Generated by Django 4.0.3 on 2022-11-15 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_cart_valider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='valider',
            new_name='es_valider',
        ),
    ]
