# Generated by Django 4.0.3 on 2023-07-25 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_commande_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='items',
            new_name='prod',
        ),
    ]
