# Generated by Django 4.0.3 on 2023-07-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_rename_items_commande_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='statut',
            field=models.CharField(blank=True, choices=[('en cours de traitement', 'en cours de traitement'), ('fini', 'traitement fini'), ('livraison en cours', 'livraison en cours'), ('livré', 'livré')], default='en cours', max_length=100, null=True),
        ),
    ]
