# Generated by Django 4.0.3 on 2023-07-27 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_commande_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered',
        ),
    ]
