# Generated by Django 4.0.3 on 2023-07-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_order_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(blank=True, choices=[('en cours de traitement', 'en cours de traitement'), ('fini', 'traitement fini'), ('livraison en cours', 'livraison en cours'), ('livré', 'livré')], max_length=100, null=True),
        ),
    ]
