# Generated by Django 4.0.3 on 2023-07-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_commande_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='image_slider'),
        ),
        migrations.AddField(
            model_name='slider',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='image_slider'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_slider'),
        ),
    ]
