# Generated by Django 4.0.3 on 2023-07-27 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_slider_image2_slider_image3_alter_slider_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='image3',
        ),
    ]
