# Generated by Django 4.0.3 on 2024-02-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_remove_slider_image2_remove_slider_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.IntegerField(null=True),
        ),
    ]
