# Generated by Django 4.0.3 on 2024-02-03 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_user_telephone'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
