# Generated by Django 4.0.3 on 2024-02-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, null=True)),
                ('image1', models.ImageField(upload_to='images_promo')),
                ('image2', models.ImageField(upload_to='images_promo')),
                ('image3', models.ImageField(upload_to='images_promo')),
                ('discount', models.IntegerField()),
            ],
        ),
    ]
